sudo: true
language: python
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- pypy
- pypy3
install:
- pip install -r requirements.txt
- pip install coveralls
- python setup.py develop
before_script: flake8 simian
script: nosetests --with-coverage --cover-package=simian simian/test
after_success: coveralls
deploy:
  provider: pypi
  user: themattrix
  password:
    secure: Iuq/qct1Oe/3BMahHv6pakhOj+BiHxCsUc8F5l/RMVqeSM9823qJaKhOgddo2B2dqRIrGvSgn3KsZDq97I46MjnhoyAKMY8OlIPpFieisjkUtq/xUAA08CmQd9Qu9tYkQg+S6dQscnrJMKxS1flj6zI8QETr+K7jmrwi250MuOk=
  on:
    python: 2.7
    tags: true
    all_branches: true
    repo: themattrix/python-simian
