sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py develop
before_script: flake8 simian
script: nosetests --with-coverage --cover-package=simian simian/test
after_success: coveralls
